apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ required "A valid .Values.name entry required!" .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "sealed-secrets-template.name" . }}
    chart: {{ include "sealed-secrets-template.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  encryptedData:
  {{- range $key, $value := .Values.sealedSecrets }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  template:
    metadata:
      creationTimestamp: null
      name: {{ include "sealed-secrets-template.name" . }}
      namespace: {{ .Release.Namespace }}
